
// resizing render 
// state clouesrs 
// action .pyload

//3  item add then redirect to detail page 

// 4  How did you implement the API integrations? (fetch /axios/others)

// 5 show an example of useReducer

//  6 Implement React.lazy

// 7 Implement React.memo

// 8 do proper form validation

// 9  add loaders or spinners

// 10 hide the sell button if the user is not loggedin

// 11  custom hook

//12  useMemo - store a value and show

// 13 using useReducer - counter 
// - create 2 input fields and check whether the data entered in those 2 fields are matching or not.

// 14  how to update data in context

//15  Create a component to find the square of a number using useMemo. If the same value is passed, it shouldn't recalculate.


//16  Create a calculator using useContext.

//17 Implement a to-do list using useReducer (partially done).

//18 Implement a counter using useContext.

//19 Add item to list using useReducer hook.

//20 Create counter app using useCallback.

//21 Timer functions using useRef with start and stop

//22 Implement HOC with example.

//23 Workout: save user data in context & use it in components.

//24 Implement routing protection (partially done)

//25 Workout: increment and decrement counter using useContext

